CREATE OR REPLACE TABLE `uber_de_yt.tbl_analytics` AS (
SELECT 
f.trip_id,
f.VendorID,
d.tpep_pickup_datetime,
d.tpep_dropoff_datetime,
p.passenger_count,
t.trip_distance,
r.rate_code_name,
pick.pickup_latitude,
pick.pickup_longitude,
drop.dropoff_latitude,
drop.dropoff_longitude,
pay.payment_type_name,
f.fare_amount,
f.extra,
f.mta_tax,
f.tip_amount,
f.tolls_amount,
f.improvement_surcharge,
f.total_amount
FROM 

`uber_de_yt.fact_table` f
JOIN `uber_de_yt.datetime_dim` d  ON f.datetime_id=d.datetime_id
JOIN `uber_de_yt.passenger_count_dim` p ON p.passenger_count_id=f.passenger_count_id  
JOIN `uber_de_yt.trip_distance_dim` t  ON t.trip_distance_id=f.trip_distance_id  
JOIN `uber_de_yt.rate_code_dim` r ON r.rate_code_id=f.rate_code_id  
JOIN `uber_de_yt.pickup_location_dim` pick ON pick.pickup_location_id=f.pickup_location_id
JOIN `uber_de_yt.drop_location_dim` drop ON drop.drop_location_id=f.drop_location_id
JOIN `uber_de_yt.payment_type_dim` pay ON pay.payment_type_id=f.payment_type_id)

--- Find top 10 pickup locations based on number of trips
--- Find total number of trips by passenger count
--- Find the average fare amount by hour of the day



🧭 1. Data Overview

What is the total number of trips recorded in the dataset?

What is the time range (start and end dates) of the dataset?

What are the average values for distance, total fare, tip, and passenger count?

Are there any missing or abnormal values in key metrics like fare, tip, or distance?

🚕 2. Revenue & Fare Analysis

What is the total revenue generated by Uber trips during the dataset period?

What is the daily trend of total revenue and average fare per trip?

Which vendor contributed the most to total revenue?

What is the distribution of total fare amounts (e.g., low, medium, high-value trips)?

How does fare vary across different days of the week and months?

📍 3. Location Insights

Which are the top 10 most frequent pickup locations?

Which are the top 10 most frequent drop-off locations?

Are there specific pickup-dropoff pairs that occur most often?

Are there areas that generate higher average fares or tips?

How does distance vary by pickup and drop-off locations?

⏰ 4. Time-Based Patterns

What are the busiest hours of the day for trips?

Which days of the week have the most trips?

How does total revenue change throughout the day?

Is there a correlation between time of day and trip distance?

During what hours do passengers tend to give higher tips?

👥 5. Passenger Behavior

What is the average fare by passenger count?

What is the most common passenger count for Uber trips?

How do trip distance and total fare vary by passenger count?

Do trips with more passengers result in higher total fares?

Are there differences in tip behavior across passenger counts?

🛣️ 6. Trip Distance & Duration

What is the average trip distance across all trips?

What percentage of trips fall within short (<1 mile), medium (1–6 miles), and long (>10 miles) ranges?

How does the average fare vary by distance range?

Which distance range contributes the most to total revenue?

Are there trips with long distances but unexpectedly low fares?

💳 7. Payment Insights

What are the most common payment types used by customers?

Which payment type generates the highest total revenue?

Do customers using digital payments tip more compared to cash?

What percentage of total transactions are credit card vs. cash?

Is there any correlation between payment method and fare amount?

⚡ 8. Vendor & Rate Code Insights

Which vendor has the highest total revenue and number of trips?

What is the average fare and distance for each vendor?

How does rate code affect the average fare amount?

Which rate codes correspond to the longest trips or highest fares?

Do certain rate codes appear more frequently during specific times of day?

💰 9. Tip & Driver Performance

What is the average tip percentage across all trips?

How do tips vary by time of day, day of week, and trip distance?

Are tips higher for certain vendors or payment methods?

What proportion of trips include zero tips?

Do shorter or longer trips receive better tips?

📊 10. Business KPIs & Trends

What are the key performance indicators (KPIs) for this dataset (revenue, trip count, avg. distance, avg. fare)?

How has Uber’s total revenue changed over time (daily, weekly, monthly)?

What is the average fare per mile (unit revenue)?

What are the peak revenue hours and low-demand periods?

Are there any seasonal patterns in trip volume or fare amount?

🌎 11. Advanced Insights (for Tableau/Looker)

Can we build a heatmap of trip density based on pickup locations?

Which geographic zones generate the most total revenue?

How does average fare correlate with pickup time and location?

What’s the top 5% of trips by revenue contribution?

Can we visualize trip distance vs. fare to identify outliers?



# Uber Trips Data Analysis

This repository contains a comprehensive analysis of Uber trips dataset. The analysis explores key metrics such as revenue, trip distance, passenger behavior, fare patterns, and temporal and geographic insights.

---

## 🧭 1. Data Overview

- **Total Trips:** Total number of trips recorded in the dataset.  
- **Time Range:** Start and end dates of the dataset.  
- **Average Metrics:** 
  - Distance
  - Total fare
  - Tip
  - Passenger count  
- **Data Quality Checks:** Identification of missing or abnormal values in key metrics like fare, tip, or distance.

---

## 🚕 2. Revenue & Fare Analysis

- **Total Revenue:** Total revenue generated by Uber trips.  
- **Daily Trends:** Total revenue and average fare per trip over time.  
- **Top Vendor:** Vendor contributing the most to total revenue.  
- **Fare Distribution:** Categorization of fares (low, medium, high-value trips).  
- **Temporal Fare Analysis:** Variation of fare across days of the week and months.

---

## 📍 3. Location Insights

- **Top Pickup Locations:** 10 most frequent pickup points.  
- **Top Drop-off Locations:** 10 most frequent drop-off points.  
- **Frequent Routes:** Common pickup-dropoff pairs.  
- **High Revenue Areas:** Locations generating higher average fares or tips.  
- **Distance by Location:** Variation of trip distance based on pickup and drop-off locations.

---

## ⏰ 4. Time-Based Patterns

- **Busiest Hours:** Peak hours for trips.  
- **Trips by Day:** Days of the week with the most trips.  
- **Revenue by Hour:** Changes in total revenue throughout the day.  
- **Distance & Time Correlation:** Relationship between trip distance and time of day.  
- **Tip Patterns:** Hours when passengers tend to give higher tips.

---

## 👥 5. Passenger Behavior

- **Average Fare by Passenger Count**  
- **Most Common Passenger Count**  
- **Distance & Fare by Passenger Count**  
- **Impact of More Passengers:** Effect on total fare.  
- **Tip Behavior:** Differences in tipping across passenger counts.

---

## 🛣️ 6. Trip Distance & Duration

- **Average Trip Distance**  
- **Trip Distance Categories:** Short (<1 mile), Medium (1–6 miles), Long (>10 miles)  
- **Fare by Distance Range**  
- **Revenue Contribution by Distance Range**  
- **Distance-Fare Outliers:** Long trips with unexpectedly low fares

---

## 💳 7. Payment Insights

- **Common Payment Types**  
- **Revenue by Payment Type**  
- **Tip Behavior by Payment Method**  
- **Payment Method Distribution:** Credit card vs. cash  
- **Payment-Fare Correlation**  

---

## ⚡ 8. Vendor & Rate Code Insights

- **Vendor Performance:** Total revenue and number of trips per vendor  
- **Average Fare & Distance per Vendor**  
- **Rate Code Analysis:** Impact on fare and trip distance  
- **Time-Based Rate Code Trends**  

---

## 💰 9. Tip & Driver Performance

- **Average Tip Percentage**  
- **Tip Variation:** By time of day, day of week, and trip distance  
- **Tips by Vendor or Payment Method**  
- **Zero-Tip Trips:** Proportion of trips with no tips  
- **Trip Length vs. Tip Analysis**

---

## 📊 10. Business KPIs & Trends

- **Key Performance Indicators (KPIs):**
  - Total Revenue
  - Total Trip Count
  - Average Distance
  - Average Fare  
- **Revenue Trends:** Daily, weekly, monthly analysis  
- **Average Fare per Mile**  
- **Peak Revenue Hours & Low-Demand Periods**  
- **Seasonal Patterns:** Trip volume and fare trends

---

## 🌎 11. Advanced Insights (for Tableau/Looker)

- **Trip Density Heatmap:** Visualization of pickup locations  
- **Revenue by Geographic Zone**  
- **Fare Correlation:** Pickup time vs. fare  
- **Top 5% Trips by Revenue Contribution**  
- **Distance vs. Fare Outliers Visualization**

---

## 📂 Repository Structure

